# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'imageProcess.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_imageProcess(object):
    def setupUi(self, imageProcess):
        imageProcess.setObjectName("imageProcess")
        imageProcess.resize(1064, 600)
        self.centralwidget = QtWidgets.QWidget(imageProcess)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        imageProcess.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(imageProcess)
        self.statusbar.setObjectName("statusbar")
        imageProcess.setStatusBar(self.statusbar)
        self.actionSet = QtWidgets.QAction(imageProcess)
        self.actionSet.setObjectName("actionSet")
        self.actionParams = QtWidgets.QAction(imageProcess)
        self.actionParams.setObjectName("actionParams")
        self.actionTab = QtWidgets.QAction(imageProcess)
        self.actionTab.setObjectName("actionTab")

        self.retranslateUi(imageProcess)
        QtCore.QMetaObject.connectSlotsByName(imageProcess)

    def retranslateUi(self, imageProcess):
        _translate = QtCore.QCoreApplication.translate
        imageProcess.setWindowTitle(_translate("imageProcess", "SEMImageProcess"))
        self.actionSet.setText(_translate("imageProcess", "配置"))
        self.actionParams.setText(_translate("imageProcess", "参数配置"))
        self.actionTab.setText(_translate("imageProcess", "页面配置"))
