# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tab1_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_tab1_imageProcess(object):
    def setupUi(self, tab1_imageProcess):
        tab1_imageProcess.setObjectName("tab1_imageProcess")
        tab1_imageProcess.resize(1072, 616)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(tab1_imageProcess)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_2 = QtWidgets.QLabel(tab1_imageProcess)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_6.addWidget(self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(tab1_imageProcess)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_6.addWidget(self.lineEdit_2)
        self.testbutton = QtWidgets.QPushButton(tab1_imageProcess)
        self.testbutton.setObjectName("testbutton")
        self.horizontalLayout_6.addWidget(self.testbutton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label = QtWidgets.QLabel(tab1_imageProcess)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(tab1_imageProcess)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_5.addWidget(self.lineEdit)
        self.pushButton = QtWidgets.QPushButton(tab1_imageProcess)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_5.addWidget(self.pushButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.plotView = PlotWidget(tab1_imageProcess)
        self.plotView.setObjectName("plotView")
        self.horizontalLayout_2.addWidget(self.plotView)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 1)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)

        self.retranslateUi(tab1_imageProcess)
        QtCore.QMetaObject.connectSlotsByName(tab1_imageProcess)

    def retranslateUi(self, tab1_imageProcess):
        _translate = QtCore.QCoreApplication.translate
        tab1_imageProcess.setWindowTitle(_translate("tab1_imageProcess", "Form"))
        self.label_2.setText(_translate("tab1_imageProcess", "端口号码"))
        self.testbutton.setText(_translate("tab1_imageProcess", "连接数据"))
        self.label.setText(_translate("tab1_imageProcess", "目标电流"))
        self.lineEdit.setText(_translate("tab1_imageProcess", "0.1"))
        self.pushButton.setText(_translate("tab1_imageProcess", "电流控制"))
from pyqtgraph import PlotWidget
