# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tab2_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_tab2_imageProcess(object):
    def setupUi(self, tab2_imageProcess):
        tab2_imageProcess.setObjectName("tab2_imageProcess")
        tab2_imageProcess.resize(957, 666)
        self.horizontalLayout = QtWidgets.QHBoxLayout(tab2_imageProcess)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.testBtn = QtWidgets.QPushButton(tab2_imageProcess)
        self.testBtn.setObjectName("testBtn")
        self.horizontalLayout_6.addWidget(self.testBtn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.verticalLayout_7.addLayout(self.horizontalLayout_6)
        self.verticalLayout_7.setStretch(0, 1)
        self.horizontalLayout.addLayout(self.verticalLayout_7)
        self.horizontalLayout.setStretch(0, 1)

        self.retranslateUi(tab2_imageProcess)
        QtCore.QMetaObject.connectSlotsByName(tab2_imageProcess)

    def retranslateUi(self, tab2_imageProcess):
        _translate = QtCore.QCoreApplication.translate
        tab2_imageProcess.setWindowTitle(_translate("tab2_imageProcess", "Form"))
        self.testBtn.setText(_translate("tab2_imageProcess", "testbutton"))
